FROM 34334:base

#add configs for supervisord
#USER root
#RUN sysctl -w net.ipv4.ip_forward=1
ADD supervisor_inet.conf /etc/supervisor/conf.d/supervisor_inet.conf

#ADD start_inet.py /start_inet.py

