ARG VERSION="11"
FROM debian:${VERSION}
ARG VERSION
RUN apt-get update # && apt-get  -y upgrade
RUN apt-get install -y curl gpg make nano procps git
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN echo "deb http://download.opensuse.org/repositories/home:/p4lang/Debian_${VERSION}/ /" | tee /etc/apt/sources.list.d/home:p4lang.list
RUN curl -fsSL "https://download.opensuse.org/repositories/home:p4lang/Debian_${VERSION}/Release.key" | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home_p4lang.gpg > /dev/null
RUN apt-get update
RUN apt-get -y install p4lang-bmv2 p4lang-p4c wget default-jre
RUN apt-get install python3-pip -y
RUN git clone https://github.com/rare-freertr/RARE-bmv2.git /rare-bmv2
RUN pip install grpcio protobuf p4runtime
# Prepare FreeRtr (includes P4Runtime code)
RUN mkdir /freertr
RUN mkdir /p4
RUN wget http://www.freertr.org/rtr.jar -O /freertr/rtr.jar
RUN apt-get install -y supervisor
WORKDIR /p4
RUN cd /p4
RUN p4c --target bmv2 --arch v1model --std p4-16 /rare-bmv2/02-PE-labs/p4src/router.p4 --p4runtime-files router.p4.p4info.txt -o router.json -v
COPY entrypoint.sh /p4/entrypoint.sh
RUN chmod +x /p4/entrypoint.sh

#ENTRYPOINT ["/p4/entrypoint.sh"]
#CMD ["bash"]
#COPY *.p4 script_translate.sh script_install.sh ./

#create directory for child images to store configuration in
RUN  mkdir -p /var/log/supervisor && mkdir -p /etc/supervisor/conf.d

#supervisor base configuration
ADD supervisor.conf /etc/supervisor/supervisor.conf
#add conf for dhclient
ADD supervisor_dhclient.conf /etc/supervisor/conf.d/supervisor_dhclient.conf

# default command
CMD ["supervisord", "-c", "/etc/supervisor/supervisor.conf"]
